"""
Router for tesseract.
"""
from fastapi import APIRouter, UploadFile
from utils import tesseract as tesseract_helper
router = APIRouter(prefix="/tesseract",
                   tags=["tesseract"])


@router.get("/supported_formats/")
async def get_supported_formats():
    """
    return supported file formats by the current version of the api.
    """
    try:
        return tesseract_helper.SUPPORTED_TYPES
    except Exception:
        print(str(Exception))
        raise


@router.post("/image_to_text/")
async def image_to_text(file: UploadFile):
    """
    return ocr json generated by tesseract for given input.
    """
    try:
        await file.read()
        tesseract_helper.validate_file_type(file)
        file_path = tesseract_helper.download_file(file)
        output_path = tesseract_helper.image_to_text(file_path)
        try:
            tesseract_helper.delete_files([file_path, output_path])
        except Exception:
            print(str(Exception))
        return {"output_path": output_path}
    except Exception:
        try:
            tesseract_helper.delete_files([file_path])
        except Exception:
            print(str(Exception))
        print(str(Exception))
        raise
